# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "./lib/private_strategy.rb"
class Awscreds2 < Formula
  desc "AWS Tools for managing credentials"
  homepage "https://github.com/jacobfg/awscreds2"
  version "0.0.2"
  license "Apache-2.0"
  depends_on :macos

  on_intel do
    url "https://github.com/jacobfg/awscreds2/releases/download/0.0.2/awscreds2_0.0.2_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "5ca73aa3243d8449b1e411a97777e73f6834b512d42f100f9387403f90f25d35"

    def install
      bin.install "awscreds"
    end
  end
  on_arm do
    url "https://github.com/jacobfg/awscreds2/releases/download/0.0.2/awscreds2_0.0.2_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "75e0186d03d7054a6049a897e3cbdee48e86e8f7509a7dd56464213c90c2f13a"

    def install
      bin.install "awscreds"
    end
  end

  test do
    system "#{bin}/awscreds version"
    assert_match "awscreds: 0.0.2 (f8924ee)", shell_output("#{bin}/awscreds version")
  end
end
