# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "./lib/private_strategy.rb"
class Awscreds < Formula
  desc "AWS Tools for managing credentials"
  homepage "https://github.com/jacobfg/awscreds"
  version "0.4.0"
  license "Apache-2.0"
  bottle :unneeded
  depends_on :macos

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jacobfg/awscreds/releases/download/0.4.0/awscreds_0.4.0_darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "cc11aa25b22715b23c46b49aa383e06a634d9d683b77192fbc68248afd433a79"
    end
    if Hardware::CPU.arm?
      url "https://github.com/jacobfg/awscreds/releases/download/0.4.0/awscreds_0.4.0_darwin_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "284f4644fe87b3f6e8b956d79980baab0ef5661f66bf1b3bbd6ade57a3cede9c"
    end
  end

  def install
    bin.install "awscreds"
    mkdir_p "#{share}/zsh/site-functions"
    oldpath = "#{prefix}/bin"
    ENV['PATH'] = "#{prefix}/bin"
    output = %x[awscreds completion zsh]
    File.write("#{share}/zsh/site-functions/_awscreds", output)
    ENV['PATH'] = oldpath
  end

  test do
    system "#{bin}/awscreds version"
  end
end
