# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "./lib/private_strategy.rb"
class Awscreds < Formula
  desc "AWS Tools for managing credentials"
  homepage "https://github.com/jacobfg/awscreds"
  version "0.4.11"
  license "Apache-2.0"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jacobfg/awscreds/releases/download/0.4.11/awscreds_0.4.11_darwin_arm64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "6ff9f0c9c98cc770f4f3735eef5e34aaf1045007fb0118ee8b0279bce85d664b"

      def install
        bin.install "awscreds"
        bash_completion.install "completions/awscreds.bash" => "awscreds"
        zsh_completion.install "completions/awscreds.zsh" => "_awscreds"
        fish_completion.install "completions/awscreds.fish"
        man1.install "manpages/awscreds.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jacobfg/awscreds/releases/download/0.4.11/awscreds_0.4.11_darwin_amd64.tar.gz", :using => GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1f5aa84c2f2e0f9f0ef29ba4a6538630d0955c7d19c97b0e65df3115bf443faa"

      def install
        bin.install "awscreds"
        bash_completion.install "completions/awscreds.bash" => "awscreds"
        zsh_completion.install "completions/awscreds.zsh" => "_awscreds"
        fish_completion.install "completions/awscreds.fish"
        man1.install "manpages/awscreds.1.gz"
      end
    end
  end

  test do
    system "#{bin}/awscreds version"
    # test version to ensure that version number is embedded in binary
    # somehow add os/arch in version output
    assert_match "awscreds: 0.4.11 (e7eb637)", shell_output("#{bin}/awscreds version")
    # assert_match "built by #{tap.user}", shell_output("#{bin}/awscreds version")
  end
end
