# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "./lib/private_strategy.rb"
class Awsprofile < Formula
  desc "AWS tools for managing terminal profiles"
  homepage "https://github.com/jacobfg/awsprofile"
  version "0.0.4"
  license "Apache-2.0"
  depends_on :macos

  on_intel do
    url "https://github.com/jacobfg/awsprofile/releases/download/0.0.4/awsprofile_0.0.4_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "5cf299033c59a6ab5fd27d7d2a6452f468335f898a88712c2f2b24d11d5e10fd"

    def install
      # bin.install "awsprofile"
      # bash_completion.install "awsprofile.bash" => "awsprofile"
      # zsh_completion.install "awsprofile.zsh" => "_awsprofile"
      # fish_completion.install "awsprofile.fish"

      bin.install "awsprofile" => "awsprofile"
      output = Utils.popen_read("SHELL=bash PATH=#{bin}:#{PATH} awsprofile completion bash")
      (bash_completion/"awsprofile").write output
      output = Utils.popen_read("SHELL=zsh PATH=#{bin}:#{PATH} awsprofile completion zsh")
      (zsh_completion/"_awsprofile").write output
      prefix.install_metafiles

      # man1.install "manpages/awsprofile.1.gz"
    end
  end
  on_arm do
    url "https://github.com/jacobfg/awsprofile/releases/download/0.0.4/awsprofile_0.0.4_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "921dcda187c15bc674a591dcfa06227fc925a55ccab8ed39a2cd796e3237809f"

    def install
      # bin.install "awsprofile"
      # bash_completion.install "awsprofile.bash" => "awsprofile"
      # zsh_completion.install "awsprofile.zsh" => "_awsprofile"
      # fish_completion.install "awsprofile.fish"

      bin.install "awsprofile" => "awsprofile"
      output = Utils.popen_read("SHELL=bash PATH=#{bin}:#{PATH} awsprofile completion bash")
      (bash_completion/"awsprofile").write output
      output = Utils.popen_read("SHELL=zsh PATH=#{bin}:#{PATH} awsprofile completion zsh")
      (zsh_completion/"_awsprofile").write output
      prefix.install_metafiles

      # man1.install "manpages/awsprofile.1.gz"
    end
  end

  test do
    system "#{bin}/awsprofile version"
    assert_match "awsprofile: 0.0.4 (cf5f607)", shell_output("#{bin}/awsprofile version")
  end
end
