# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "./lib/private_strategy.rb"
class Awsprofile < Formula
  desc "AWS tools for managing terminal profiles"
  homepage "https://github.com/jacobfg/awsprofile"
  version "0.0.3"
  license "Apache-2.0"
  depends_on :macos

  on_intel do
    url "https://github.com/jacobfg/awsprofile/releases/download/0.0.3/awsprofile_0.0.3_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "e3dd876efe5c71c01d5124ed3d6f4f2d15683eb7479e5250994fb267653c73ea"

    def install
      # bin.install "awsprofile"
      # bash_completion.install "awsprofile.bash" => "awsprofile"
      # zsh_completion.install "awsprofile.zsh" => "_awsprofile"
      # fish_completion.install "awsprofile.fish"

      bin.install "awsprofile" => "awsprofile"
      output = Utils.popen_read("SHELL=bash PATH=#{bin}:#{PATH} awsprofile completion bash")
      (bash_completion/"awsprofile").write output
      output = Utils.popen_read("SHELL=zsh PATH=#{bin}:#{PATH} awsprofile completion zsh")
      (zsh_completion/"_awsprofile").write output
      prefix.install_metafiles

      # man1.install "manpages/awsprofile.1.gz"
    end
  end
  on_arm do
    url "https://github.com/jacobfg/awsprofile/releases/download/0.0.3/awsprofile_0.0.3_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "fb12e317e2a363623afa114c952c203b43b452f72d0cdd1ba3709d764a6e1473"

    def install
      # bin.install "awsprofile"
      # bash_completion.install "awsprofile.bash" => "awsprofile"
      # zsh_completion.install "awsprofile.zsh" => "_awsprofile"
      # fish_completion.install "awsprofile.fish"

      bin.install "awsprofile" => "awsprofile"
      output = Utils.popen_read("SHELL=bash PATH=#{bin}:#{PATH} awsprofile completion bash")
      (bash_completion/"awsprofile").write output
      output = Utils.popen_read("SHELL=zsh PATH=#{bin}:#{PATH} awsprofile completion zsh")
      (zsh_completion/"_awsprofile").write output
      prefix.install_metafiles

      # man1.install "manpages/awsprofile.1.gz"
    end
  end

  test do
    system "#{bin}/awsprofile version"
    assert_match "awsprofile: 0.0.3 (5688a63)", shell_output("#{bin}/awsprofile version")
  end
end
