# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "./lib/private_strategy.rb"
class Awsprofile < Formula
  desc "AWS Tools for managing credentials"
  homepage "https://github.com/jacobfg/awsprofile"
  version "0.0.1"
  license "Apache-2.0"
  depends_on :macos

  on_intel do
    url "https://github.com/jacobfg/awsprofile/releases/download/0.0.1/awsprofile_0.0.1_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "f3ebe18f7b944162c326e8f924b4fdfe86c43bc76031a3ea7d92825af4e356b5"

    def install
      bin.install "awsprofile"
      bash_completion.install "awsprofile.bash" => "awsprofile"
      zsh_completion.install "awsprofile.zsh" => "_awsprofile"
      fish_completion.install "awsprofile.fish"
      # man1.install "manpages/awsprofile.1.gz"
    end
  end
  on_arm do
    url "https://github.com/jacobfg/awsprofile/releases/download/0.0.1/awsprofile_0.0.1_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "5e91244af70c944dac2425081c803d6f08e002bab4a522852dd515ebacf01bf2"

    def install
      bin.install "awsprofile"
      bash_completion.install "awsprofile.bash" => "awsprofile"
      zsh_completion.install "awsprofile.zsh" => "_awsprofile"
      fish_completion.install "awsprofile.fish"
      # man1.install "manpages/awsprofile.1.gz"
    end
  end

  test do
    system "#{bin}/awsprofile version"
    assert_match "awsprofile: 0.0.1 (330e5da)", shell_output("#{bin}/awsprofile version")
  end
end
