# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "./lib/private_strategy.rb"
class Awsudo < Formula
  desc "AWS Tools running a CLI program as a different AWS profile / ARN"
  homepage "https://github.com/jacobfg/awsudo"
  version "0.0.2"
  license "Apache-2.0"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jacobfg/awsudo/releases/download/0.0.2/awsudo_0.0.2_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f181eb2e6de7c6e755c98119c69eb4f59848f917c3a8ee9a3a2321f7cc0211ea"

      def install
        bin.install "awsudo"
        bash_completion.install "completions/awsudo.bash" => "awsudo"
        zsh_completion.install "completions/awsudo.zsh" => "_awsudo"
        fish_completion.install "completions/awsudo.fish"
        # man1.install "manpages/awsudo.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jacobfg/awsudo/releases/download/0.0.2/awsudo_0.0.2_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "b27f9e0cf9b5325f566285bbef03adf2834f215db5314eed1b90019a565df201"

      def install
        bin.install "awsudo"
        bash_completion.install "completions/awsudo.bash" => "awsudo"
        zsh_completion.install "completions/awsudo.zsh" => "_awsudo"
        fish_completion.install "completions/awsudo.fish"
        # man1.install "manpages/awsudo.1.gz"
      end
    end
  end

  test do
    system "#{bin}/awsudo version"
    # test version to ensure that version number is embedded in binary
    # somehow add os/arch in version output
    assert_match "awsudo: 0.0.2 (4dba549)", shell_output("#{bin}/awsudo version")
    # assert_match "built by #{tap.user}", shell_output("#{bin}/awsudo version")
  end
end
