# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "./lib/private_strategy.rb"
class JacobfgTools < Formula
  desc "CLI tools"
  homepage "https://github.com/jacobfg/okta-session-login"
  version "0.0.8"
  license "Apache-2.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/jacobfg/okta-session-login/releases/download/0.0.8/okta-session-login_0.0.8_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "528171d284131eeba2ca76bb6f57d4745acb2e6f4e89dd14da5bd92b98298a0d"

    def install
      bin.install "cert-details" => "cert-details"
      bin.install "totp" => "totp"
      bin.install "httpdecode" => "httpdecode"
      bin.install "httpencode" => "httpencode"
      bin.install "osx-app-setup" => "osx-app-setup"
      bin.install "ini-print" => "ini-print"
      bin.install "cli-select" => "cli-select"
      prefix.install_metafiles
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/jacobfg/okta-session-login/releases/download/0.0.8/okta-session-login_0.0.8_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "b263e75ae54ca25e82d37ad02a4a60a6046909637c66e18f684e63b3a2ec246e"

    def install
      bin.install "cert-details" => "cert-details"
      bin.install "totp" => "totp"
      bin.install "httpdecode" => "httpdecode"
      bin.install "httpencode" => "httpencode"
      bin.install "osx-app-setup" => "osx-app-setup"
      bin.install "ini-print" => "ini-print"
      bin.install "cli-select" => "cli-select"
      prefix.install_metafiles
    end
  end
end
