# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "./lib/private_strategy.rb"
class OktaGpgCreds < Formula
  desc "CLI tools for Okta creds"
  homepage "https://github.com/jacobfg/okta-session-login"
  version "0.0.2"
  license "Apache-2.0"
  depends_on :macos

  on_intel do
    url "https://github.com/jacobfg/okta-session-login/releases/download/0.0.2/okta-session-login_0.0.2_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "fb5bcddcf12a79dd60294f177a9a8487b5ef4e521372e02866595eaaad4625f5"

    def install
      bin.install "okta-gpg-creds" => "okta-gpg-creds"
      prefix.install_metafiles
    end
  end
  on_arm do
    url "https://github.com/jacobfg/okta-session-login/releases/download/0.0.2/okta-session-login_0.0.2_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "5d3e9d53087c9c05988e1722e6f2dc5942769fa88fa678f68831b77939c84ed5"

    def install
      bin.install "okta-gpg-creds" => "okta-gpg-creds"
      prefix.install_metafiles
    end
  end
end
