# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "./lib/private_strategy.rb"
class OktaSessionLogin < Formula
  desc "CLI tools for working with FIT files"
  homepage "https://github.com/jacobfg/okta-session-login"
  version "0.0.2"
  license "Apache-2.0"
  depends_on :macos

  on_intel do
    url "https://github.com/jacobfg/okta-session-login/releases/download/0.0.2/okta-session-login_0.0.2_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "fb5bcddcf12a79dd60294f177a9a8487b5ef4e521372e02866595eaaad4625f5"

    def install
      # bin.install "okta-session-login"
      # bash_completion.install "okta-session-login.bash" => "okta-session-login"
      # zsh_completion.install "okta-session-login.zsh" => "_okta-session-login"
      # fish_completion.install "okta-session-login.fish"

      bin.install "okta-session-login" => "okta-session-login"
      output = Utils.popen_read("SHELL=bash PATH=#{bin}:#{PATH} okta-session-login completion bash")
      (bash_completion/"okta-session-login").write output
      output = Utils.popen_read("SHELL=zsh PATH=#{bin}:#{PATH} okta-session-login completion zsh")
      (zsh_completion/"_okta-session-login").write output
      prefix.install_metafiles

      # man1.install "manpages/okta-session-login.1.gz"
    end
  end
  on_arm do
    url "https://github.com/jacobfg/okta-session-login/releases/download/0.0.2/okta-session-login_0.0.2_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "5d3e9d53087c9c05988e1722e6f2dc5942769fa88fa678f68831b77939c84ed5"

    def install
      # bin.install "okta-session-login"
      # bash_completion.install "okta-session-login.bash" => "okta-session-login"
      # zsh_completion.install "okta-session-login.zsh" => "_okta-session-login"
      # fish_completion.install "okta-session-login.fish"

      bin.install "okta-session-login" => "okta-session-login"
      output = Utils.popen_read("SHELL=bash PATH=#{bin}:#{PATH} okta-session-login completion bash")
      (bash_completion/"okta-session-login").write output
      output = Utils.popen_read("SHELL=zsh PATH=#{bin}:#{PATH} okta-session-login completion zsh")
      (zsh_completion/"_okta-session-login").write output
      prefix.install_metafiles

      # man1.install "manpages/okta-session-login.1.gz"
    end
  end

  test do
    system "#{bin}/okta-session-login version"
    assert_match "okta-session-login: 0.0.2 (9d5cef3)", shell_output("#{bin}/okta-session-login version")
  end
end
