# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "./lib/private_strategy.rb"
class OktaSessionLogin < Formula
  desc "CLI tools for working with FIT files"
  homepage "https://github.com/jacobfg/okta-session-login"
  version "0.0.6"
  license "Apache-2.0"
  depends_on :macos

  on_intel do
    url "https://github.com/jacobfg/okta-session-login/releases/download/0.0.6/okta-session-login_0.0.6_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "547c75fe41af333c0542eb4848f837a5cde7917c1fb1bdb6443ab995067f24ce"

    def install
      # bin.install "okta-session-login"
      # bash_completion.install "okta-session-login.bash" => "okta-session-login"
      # zsh_completion.install "okta-session-login.zsh" => "_okta-session-login"
      # fish_completion.install "okta-session-login.fish"

      bin.install "okta-session-login" => "okta-session-login"
      output = Utils.popen_read("SHELL=bash PATH=#{bin}:#{PATH} okta-session-login completion bash")
      (bash_completion/"okta-session-login").write output
      output = Utils.popen_read("SHELL=zsh PATH=#{bin}:#{PATH} okta-session-login completion zsh")
      (zsh_completion/"_okta-session-login").write output
      prefix.install_metafiles

      # man1.install "manpages/okta-session-login.1.gz"
    end
  end
  on_arm do
    url "https://github.com/jacobfg/okta-session-login/releases/download/0.0.6/okta-session-login_0.0.6_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "5104c16ee796d7d10bbd2531b0bac9856c51ec54cdd868dc6f451522ab7b118a"

    def install
      # bin.install "okta-session-login"
      # bash_completion.install "okta-session-login.bash" => "okta-session-login"
      # zsh_completion.install "okta-session-login.zsh" => "_okta-session-login"
      # fish_completion.install "okta-session-login.fish"

      bin.install "okta-session-login" => "okta-session-login"
      output = Utils.popen_read("SHELL=bash PATH=#{bin}:#{PATH} okta-session-login completion bash")
      (bash_completion/"okta-session-login").write output
      output = Utils.popen_read("SHELL=zsh PATH=#{bin}:#{PATH} okta-session-login completion zsh")
      (zsh_completion/"_okta-session-login").write output
      prefix.install_metafiles

      # man1.install "manpages/okta-session-login.1.gz"
    end
  end

  test do
    system "#{bin}/okta-session-login version"
    assert_match "okta-session-login: 0.0.6 (a108181)", shell_output("#{bin}/okta-session-login version")
  end
end
