# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "./lib/private_strategy.rb"
class OktaGpgCreds < Formula
  desc "CLI tools for Okta creds"
  homepage "https://github.com/jacobfg/okta-session-login"
  version "0.0.7"
  license "Apache-2.0"
  depends_on :macos

  on_intel do
    url "https://github.com/jacobfg/okta-session-login/releases/download/0.0.7/okta-session-login_0.0.7_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "28f1a6d0922f469ab1a3b26115a1d8b6dc5459e5690908bc44c6ea17bf72d1b3"

    def install
      bin.install "okta-gpg-creds" => "okta-gpg-creds"
      prefix.install_metafiles
    end
  end
  on_arm do
    url "https://github.com/jacobfg/okta-session-login/releases/download/0.0.7/okta-session-login_0.0.7_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "98d0677d684e7e6d6f0dd5230050ff1bd58bbd597b276ca22c3c9d545625e247"

    def install
      bin.install "okta-gpg-creds" => "okta-gpg-creds"
      prefix.install_metafiles
    end
  end
end
