# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "./lib/private_strategy.rb"
class OktaGpgCreds < Formula
  desc "CLI tools for Okta creds"
  homepage "https://github.com/jacobfg/okta-session-login"
  version "0.0.4"
  license "Apache-2.0"
  depends_on :macos

  on_intel do
    url "https://github.com/jacobfg/okta-session-login/releases/download/0.0.4/okta-session-login_0.0.4_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "521c19439170fb8e08b3224283264a0623c1d949c3dad6c2d91d9681511a471d"

    def install
      bin.install "okta-gpg-creds" => "okta-gpg-creds"
      prefix.install_metafiles
    end
  end
  on_arm do
    url "https://github.com/jacobfg/okta-session-login/releases/download/0.0.4/okta-session-login_0.0.4_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
    sha256 "5e8e2b9efdd09e916350c812d569703cfaaea82e00a7ea2d57524deeeeebcd96"

    def install
      bin.install "okta-gpg-creds" => "okta-gpg-creds"
      prefix.install_metafiles
    end
  end
end
