# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "./lib/private_strategy.rb"
class Xlsxgrep < Formula
  desc "Grep for XLSX files"
  homepage "https://github.com/jacobfg/xlsxgrep"
  version "0.0.1"
  license "Apache-2.0"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jacobfg/xlsxgrep/releases/download/0.0.1/xlsxgrep_0.0.1_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "dd049b7c87c7d7a1299c8336e534dd1b2ccca1b12c35f8ecc35352921331ea40"

      def install
        bin.install "xslxgrep"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jacobfg/xlsxgrep/releases/download/0.0.1/xlsxgrep_0.0.1_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1b45a4291cb3668c30b833a540c48e5a9a3f84a61960f0ecaa513b9676e03d8a"

      def install
        bin.install "xslxgrep"
      end
    end
  end

  test do
    system "#{bin}/xlsxgrep version"
    assert_match "xlsxgrep: 0.0.1 (c6b80b1)", shell_output("#{bin}/xlsxgrep version")
  end
end
