# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "./lib/private_strategy.rb"
class Xlsxgrep < Formula
  desc "Grep for XLSX files"
  homepage "https://github.com/jacobfg/xlsxgrep"
  version "0.0.1"
  license "Apache-2.0"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jacobfg/xlsxgrep/releases/download/0.0.1/xlsxgrep_0.0.1_darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "80d9d4341b41da5cdb43bf71a465e83a9fe1efe033eb6cf077437a93d8282c7f"

      def install
        bin.install "xlsxgrep"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jacobfg/xlsxgrep/releases/download/0.0.1/xlsxgrep_0.0.1_darwin_amd64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "6b2546c7245d100c4054b25e35897d82e7a20ffa04e993f616d1f2c15050ecae"

      def install
        bin.install "xlsxgrep"
      end
    end
  end

  test do
    system "#{bin}/xlsxgrep version"
    assert_match "xlsxgrep: 0.0.1 (b1b6703)", shell_output("#{bin}/xlsxgrep -version")
  end
end
